# Generated by Django 4.0.2 on 2022-03-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='img_up',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
