# Generated by Django 4.0.2 on 2022-03-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_office_img_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_up', models.ImageField(default='', upload_to='gallery/')),
                ('caption', models.CharField(max_length=10000)),
            ],
        ),
    ]
